#!/bin/bash
# Regenerates every .cfg in this directory. One module; configs differ only in
# constants (Layout, bounds, consistency and mutation flags) and in which
# properties they check.
cd "$(dirname "$0")"
FLAGS="STALE_READS READER_LAG SPLIT_BARRIER SKIP_WM_READBACK OCCUPANCY_READBACK SKIP_REWRITE SKIP_CLAIM_READBACK UNSAFE_TAKEOVER"
SAFE="TypeOK AllocUnique NoDupVersion LoserInvisible CommittedVisible DoneIsPublished PinnedStable ResolvesNewest"
mk() { # name layout alloc pub skip takeovers crashes "TRUE flags" "invariants" "properties"
  { echo "\\* $1 -- generated by gen_cfgs.sh; see README.md"
    echo "SPECIFICATION Spec"
    echo "CONSTANTS"
    echo "  Layout = \"$2\""
    echo "  AllocAttempts = $3"; echo "  PublishAttempts = $4"; echo "  MaxSkip = $5"
    echo "  MaxTakeovers = $6"; echo "  MaxCrashes = $7"
    for fl in $FLAGS; do
      if [[ " $8 " == *" $fl "* ]]; then echo "  $fl = TRUE"; else echo "  $fl = FALSE"; fi
    done
    echo "INVARIANTS"; for inv in $9; do echo "  $inv"; done
    if [ -n "${10}" ]; then echo "PROPERTIES"; for pr in ${10}; do echo "  $pr"; done; fi
  } > "$1.cfg"
}
mk Faithful       shared 2 2 1 1 1 ""                   "$SAFE NeverConflict" "MonotonicLanding Termination"
mk FaithfulLarge  shared 3 3 1 1 1 ""                   "$SAFE NeverConflict" "MonotonicLanding"
# Finding: a replayed pack re-promotes itself over a newer pack (see README).
mk Replay         replay 2 2 1 0 0 ""                   "$SAFE" "MonotonicLanding"
mk ReplayRest     replay 2 2 1 0 0 "" "TypeOK AllocUnique NoDupVersion LoserInvisible CommittedVisible DoneIsPublished" "MonotonicLanding Termination"
mk ReplayCrash    replaycrash 2 2 1 0 1 "" "PinnedStable ResolvesNewest"
mk ReplayCrashPinned replaycrash 2 2 1 0 1 "" "PinnedStable"
# Consistency parameter: eventually-consistent (stale) reads.
mk StaleAlloc     pair   2 2 1 1 0 "STALE_READS"        "AllocUnique"
mk StalePublish   pair   2 2 1 1 0 "STALE_READS"        "NoDupVersion" "MonotonicLanding"
mk StaleReader    shared 2 2 1 0 0 "STALE_READS READER_LAG" "ReaderLagNoSuperseded"
# Mutations.
mk SplitBarrier   pair   2 2 1 1 0 "SPLIT_BARRIER"      "NoDupVersion PinnedStable" "MonotonicLanding"
mk UnsafeTakeover pair   2 2 1 1 0 "UNSAFE_TAKEOVER"    "NoDupVersion PinnedStable" "MonotonicLanding"
mk SkipWmReadback shared 2 2 1 0 0 "SKIP_WM_READBACK"   "CommittedVisible DoneIsPublished"
mk SkipRewrite    shared 2 2 1 0 0 "SKIP_REWRITE"       "ResolvesNewest"
mk SkipClaimReadback     pair 2 2 1 1 0 "SKIP_CLAIM_READBACK" "AllocUnique"
mk SkipClaimReadbackRest pair 2 2 1 1 1 "SKIP_CLAIM_READBACK" "TypeOK NoDupVersion LoserInvisible CommittedVisible DoneIsPublished PinnedStable ResolvesNewest" "MonotonicLanding Termination"
mk OccupancyReadback     pair 2 2 1 1 0 "SKIP_CLAIM_READBACK OCCUPANCY_READBACK" "CommittedVisible DoneIsPublished LoserInvisible"
# Reachability witnesses (each must be VIOLATED) and the no-conflict claim.
for w in NeverLostRace NeverRetryWins NeverSuccessorPub NeverFencedOut NeverOrphanLands NeverContested; do
  mk Witness$w shared 2 2 1 1 1 "" "$w"
done
